#!/bin/bash
clear

# - CORES
RED='\033[1;31m'
YELLOW='\033[1;33m'
SCOLOR='\033[0m'

# - VERIFICA EXECUÇÃO COMO ROOT
[[ "$EUID" -ne 0 ]] && {
    echo -e "${RED}[x] VC PRECISA EXECULTAR COMO USUARIO ROOT !${SCOLOR}"
    exit 1
}

# - VERIFICA ARQUITETURA COMPATIVEL
case "$(uname -m)" in
    'amd64' | 'x86_64')
        arch='AMD'
        ;;
    'aarch64' | 'armv8')
        arch='ARM64'
        ;;
    *)
        echo -e "${RED}[x] ARQUITETURA INCOMPATIVEL !${SCOLOR}"
        exit 1
        ;;
esac

# - VERIFICA SISTEMA COMPATIVEL
if grep -qs "ubuntu" /etc/os-release; then
	os_version=$(grep 'VERSION_ID' /etc/os-release | cut -d '"' -f 2 | tr -d '.')
    [[ "$os_version" -lt 1804 ]] && {
        echo -e "${RED}[x] VERSAO DO UBUNTU INCOMPATIVEL !\n${YELLOW}[!] REQUER UBUNTU 18.04 OU SUPERIOR !${SCOLOR}"
        exit 1
    }
elif [[ -e /etc/debian_version ]]; then
	os_version=$(grep -oE '[0-9]+' /etc/debian_version | head -1)
    [[ "$os_version" -lt 9 ]] && {
        echo -e "${RED}[x] VERSAO DO DEBIAN INCOMPATIVEL !\n${YELLOW}[!] REQUER DEBIAN 9 OU SUPERIOR !${SCOLOR}"
        exit 1
    }
else
    echo -e "${RED}[x] OS INCOMPATIVEL !\n${YELLOW}[!] REQUER DISTROS BASE DEBIAN/UBUNTU !${SCOLOR}"
    exit 1
fi

# - INICIA O INSTALADOR
[[ -e sshpro ]] && rm -rf sshpro
    wget https://raw.githubusercontent.com/xyzeusyx/SSH-PRO/main/Instalador/${arch}/sshpro
    chmod 777 sshpro
    ./sshpro